# Generated by Django 3.2 on 2023-04-15 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('address', models.CharField(blank=True, default='', max_length=200)),
                ('tel', models.CharField(blank=True, default='', max_length=30)),
            ],
        ),
    ]
